#!/bin/bash
if [ $PAGESPEED == 'True' ]; then
  echo "PAGESPEED is on (${PAGESPEED})"
  if [ $BROWSERCACHE == 'True' ]; then
    echo "BROWSERCACHE is on (${BROWSERCACHE})"
    exec /launch/start_with_pagespeed_and_browsercache.sh
  else
    echo "BROWSERCACHE is off (${BROWSERCACHE})"
    exec /launch/start_with_pagespeed.sh
  fi
else
  echo "NO PAGESPEED OR BROWSERCACHE... using gunicorn only"
#  exec /launch/start_with_nginx.sh
  exec /launch/start_gunicorn.sh
fi
